SELECT
A.CT1_CONTA,
A.CT1_DESC01,
CASE
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 1
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,1) = SUBSTR(A.CT1_CONTA,1,1) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 2
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,2) = SUBSTR(A.CT1_CONTA,1,2) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 3
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,3) = SUBSTR(A.CT1_CONTA,1,3) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 5
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,5) = SUBSTR(A.CT1_CONTA,1,5) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 7
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,7) = SUBSTR(A.CT1_CONTA,1,7) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
ELSE (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND B.CQ1_CONTA = A.CT1_CONTA AND B.D_E_L_E_T_ <> '*' AND B.CQ1_TPSALD = '1' AND SUBSTR(B.CQ1_DATA,1,6)<TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
END SALDO_ANTERIOR,
CASE
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 1
THEN (SELECT NVL(SUM(B.CQ1_DEBITO),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,1) = SUBSTR(A.CT1_CONTA,1,1) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 2
THEN (SELECT NVL(SUM(B.CQ1_DEBITO),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,2) = SUBSTR(A.CT1_CONTA,1,2) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 3
THEN (SELECT NVL(SUM(B.CQ1_DEBITO),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,3) = SUBSTR(A.CT1_CONTA,1,3) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 5
THEN (SELECT NVL(SUM(B.CQ1_DEBITO),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,5) = SUBSTR(A.CT1_CONTA,1,5) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 7
THEN (SELECT NVL(SUM(B.CQ1_DEBITO),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,7) = SUBSTR(A.CT1_CONTA,1,7) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
ELSE (SELECT NVL(SUM(B.CQ1_DEBITO),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND B.CQ1_CONTA = A.CT1_CONTA AND B.D_E_L_E_T_ <> '*' AND B.CQ1_TPSALD = '1' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
END DEBITO,
CASE
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 1
THEN (SELECT NVL(SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,1) = SUBSTR(A.CT1_CONTA,1,1) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 2
THEN (SELECT NVL(SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,2) = SUBSTR(A.CT1_CONTA,1,2) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 3
THEN (SELECT NVL(SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,3) = SUBSTR(A.CT1_CONTA,1,3) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 5
THEN (SELECT NVL(SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,5) = SUBSTR(A.CT1_CONTA,1,5) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 7
THEN (SELECT NVL(SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,7) = SUBSTR(A.CT1_CONTA,1,7) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
ELSE (SELECT NVL(SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND B.CQ1_CONTA = A.CT1_CONTA AND B.CQ1_TPSALD = '1'  AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
END CREDITO,
CASE
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 1
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,1) = SUBSTR(A.CT1_CONTA,1,1) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 2
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,2) = SUBSTR(A.CT1_CONTA,1,2) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 3
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,3) = SUBSTR(A.CT1_CONTA,1,3) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 5
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,5) = SUBSTR(A.CT1_CONTA,1,5) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 7
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,7) = SUBSTR(A.CT1_CONTA,1,7) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
ELSE (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND B.CQ1_CONTA = A.CT1_CONTA AND B.D_E_L_E_T_ <> '*' AND B.CQ1_TPSALD = '1' AND SUBSTR(B.CQ1_DATA,1,6)=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
END MOVIMENTO_PERIODO,
CASE
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 1
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,1) = SUBSTR(A.CT1_CONTA,1,1) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 2
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,2) = SUBSTR(A.CT1_CONTA,1,2) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 3
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,3) = SUBSTR(A.CT1_CONTA,1,3) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 5
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,5) = SUBSTR(A.CT1_CONTA,1,5) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
	WHEN LENGTH(LTRIM(RTRIM(A.CT1_CONTA))) = 7
THEN (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND SUBSTR(B.CQ1_CONTA,1,7) = SUBSTR(A.CT1_CONTA,1,7) AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
ELSE (SELECT NVL(SUM(B.CQ1_DEBITO)-SUM(B.CQ1_CREDIT),0) FROM PROTHEUS.CQ1010 B WHERE B.CQ1_MOEDA = '01' AND B.CQ1_CONTA = A.CT1_CONTA AND B.CQ1_TPSALD = '1' AND B.D_E_L_E_T_ <> '*' AND SUBSTR(B.CQ1_DATA,1,6)<=TO_CHAR(CONCAT(LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000),LPAD(EXTRACT(MONTH FROM SYSDATE),2,00))))
END SALDO_FINAL
FROM PROTHEUS.CT1010 A 
WHERE  A.D_E_L_E_T_ <> '*'
GROUP BY A.CT1_CONTA,A.CT1_DESC01 
ORDER BY A.CT1_CONTA;
