DECLARE
	nDebito  NUMBER := 0;
	nCredito NUMBER := 0;

BEGIN 

SELECT 
ABS(SUM(CQ1_DEBITO)) INTO nDebito
FROM PROTHEUS.CQ1010 
WHERE CQ1_MOEDA = '01' AND CQ1_TPSALD = '1' AND D_E_L_E_T_ <> '*' AND SUBSTR(CQ1_DATA,1,4) = '2023';

SELECT 
ABS(SUM(CQ1_CREDIT)) INTO nCredito
FROM PROTHEUS.CQ1010 
WHERE CQ1_MOEDA = '01' AND CQ1_TPSALD = '1' AND D_E_L_E_T_ <> '*' AND SUBSTR(CQ1_DATA,1,4) = '2023';


DBMS_OUTPUT.PUT_LINE('Debito = ' || TO_CHAR(nDebito));
DBMS_OUTPUT.PUT_LINE('Credito = ' || TO_CHAR(nCredito));

END;
