DECLARE
	nSldrexe  NUMBER := 0;
	nSldepr   NUMBER := 0;
	nSldepram NUMBER := 0;
	nSldamort NUMBER := 0;
	nSldresfn NUMBER := 0;
	nSldresps NUMBER := 0;
	nSldresno NUMBER := 0;
	nSlprircs NUMBER := 0;
	nSldeprgr NUMBER := 0;
	nSldamrgr NUMBER := 0;
	nSldeprac NUMBER := 0;
	nVlrebtda NUMBER := 0;
	cMes varchar(2) := LPAD(EXTRACT(MONTH FROM SYSDATE),2,00);
	cAno varchar(4) := LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000);

BEGIN
		
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldrexe  FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND SUBSTR(a.CQ1_CONTA,1,1) = '3' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldepr   FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND a.CQ1_CONTA = '3112321005' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldepram FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND a.CQ1_CONTA = '3112321007' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldamort FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND a.CQ1_CONTA = '3112321008' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldresfn FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND a.CQ1_CONTA = '3112321009' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldresps FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND a.CQ1_CONTA = '3112321010' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldresno FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND a.CQ1_CONTA = '3112321011' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSlprircs FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND SUBSTR(a.CQ1_CONTA,1,5) = '31124' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldeprgr FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND SUBSTR(a.CQ1_CONTA,1,5) = '31126' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldamrgr FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND SUBSTR(a.CQ1_CONTA,1,2) = '32' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nSldeprac FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND SUBSTR(a.CQ1_CONTA,1,5) = '34111' AND SUBSTR(CQ1_DATA,5,2) = cMes AND SUBSTR(CQ1_DATA,1,4) = cAno AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';

	nVlrebtda := round(nSldrexe + nSldepr + nSldepram + nSldamort + nSldresfn + nSldresps + nSldresno + nSlprircs + nSldeprgr + nSldamrgr + nSldeprac,2);

	DBMS_OUTPUT.PUT_LINE('EBITDA= ' || TO_CHAR(nVlrebtda));

END;
