DECLARE
	nSldpsc NUMBER := 0;
	nSldpse NUMBER := 0;
	nSldptl NUMBER := 0;
	nPtcptc NUMBER := 0;	
	cMes varchar(2) := LPAD(EXTRACT(MONTH FROM SYSDATE),2,00);
	cAno varchar(4) := LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000);

BEGIN


SELECT ROUND(sum(CQ1_DEBITO)-sum(CQ1_CREDIT),2) INTO nSldpsc FROM PROTHEUS.CQ1010 WHERE SUBSTR(CQ1_CONTA,1,2) = '21' AND D_E_L_E_T_ <> '*' AND SUBSTR(CQ1_DATA,5,2) = cMes AND cAno = SUBSTR(CQ1_DATA,1,4) AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01' ;
SELECT ROUND(sum(CQ1_DEBITO)-sum(CQ1_CREDIT),2) INTO nSldpse FROM PROTHEUS.CQ1010 WHERE SUBSTR(CQ1_CONTA,1,2) = '22' AND D_E_L_E_T_ <> '*' AND SUBSTR(CQ1_DATA,5,2) = cMes AND cAno = SUBSTR(CQ1_DATA,1,4) AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
SELECT ROUND(sum(CQ1_DEBITO)-sum(CQ1_CREDIT),2) INTO nSldptl FROM PROTHEUS.CQ1010 WHERE SUBSTR(CQ1_CONTA,1,2) = '24' AND D_E_L_E_T_ <> '*' AND SUBSTR(CQ1_DATA,5,2) = cMes AND cAno = SUBSTR(CQ1_DATA,1,4) AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';

nPtcptc := round(((nSldpsc+nSldpse)/nSldptl)*100,2);

DBMS_OUTPUT.PUT_LINE('Patr Liq poder Terc = ' || TO_CHAR(nPtcptc));

END;


