DECLARE
	nRecopbr NUMBER := 0;
	nVlded   NUMBER := 0;
	nVlrol   NUMBER := 0;
	cMes varchar(2) := LPAD(EXTRACT(MONTH FROM SYSDATE),2,00);
	cAno varchar(4) := LPAD(EXTRACT(YEAR FROM SYSDATE),4,0000);

BEGIN
	
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nRecopbr FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND SUBSTR(a.CQ1_CONTA,1,5) = '31111' AND SUBSTR(CQ1_DATA,1,4) = cAno AND SUBSTR(CQ1_DATA,5,2) = '01' AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	SELECT abs(sum(a.CQ1_DEBITO) - sum(a.CQ1_CREDIT)) INTO nVlded FROM PROTHEUS.CQ1010 a WHERE a.CQ1_TPSALD = '1' AND a.D_E_L_E_T_ <> '*'  AND SUBSTR(a.CQ1_CONTA,1,5) = '31112' AND SUBSTR(CQ1_DATA,1,4) = cAno AND SUBSTR(CQ1_DATA,5,2) = '01' AND CQ1_TPSALD = '1' AND CQ1_MOEDA = '01';
	
	nVlrol := nRecopbr - nVlded;

	DBMS_OUTPUT.PUT_LINE('ROL = ' || TO_CHAR(nVlrol));
	
END;